# Generated by Django 6.0.7 on 2026-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapuser',
            name='snap_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
