# Generated by Django 6.0.8 on 2026-08-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_is_viewed_highlight_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
